baseURL:  'http://localhost:1313/'
languageCode: 'en-gb'
theme: "gearmill"

enableRobotsTXT: true

Params:
  name: "hughie [at] hugle.uk"
  year: "2023"
  title: "Gear Mill"

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true

